max_strength: 5
def_strength: 0
min_strength: -3

strength_to_activate_ability: 5
strength_to_have_passive: 5

show_duration_in_actionbar: true

stun_axe_duration: 1
sword_ultimate_multiplier: 1.5
mace_cooldown: 30

bow_beam_damage: 4
bow_beam_range: 20

axe_nerf_damage: 3

natural_cause_lose_strength: true

shield_resistance_duration: 5
shield_resistance_amplifier: 0

time_for_losing_ready: 30

shield_kb: -1

trustSystem: true
banStrengthPotions: true

bow_beams_amount: 3
bow_beam_speed: 25
bow_first_beam_delay: 20

tridentUltSpeed: 0.8
tridentUltWaveSize: 12

visuals:
  bowRotationSpeed: 5

cooldowns:
  sword: 60
  axe: 60
  trident: 60
  shield: 60
  bow: 60
  crossbow: 60

durations:
  sword: 15
  axe: 5
  trident: 5
  shield: 15
  crossbow: 15

counters_ready:
  sword: 5
  axe: 7
  trident: 3
  shield: 0
  crossbow: 5
  bow: 10

counters_passives:
  sword: 3
  axe: 5
  trident: 1
  shield: 0
  crossbow: 3
  bow: 5

recipes:
  strength:
    shape:
      - "ENE"
      - "NSN"
      - "ENE"

    ingredients:
      E: ENCHANTED_GOLDEN_APPLE
      N: NETHERITE_INGOT
      S: NETHER_STAR

  reroll:
    shape:
      - "IGI"
      - "GDG"
      - "IGI"

    ingredients:
      I: IRON_BLOCK
      G: GOLD_BLOCK
      D: DIAMOND_BLOCK
